# Generated by Django 5.2.16 on 2026-07-17 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deliveryprofile_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_status_updated', 'Estado de pedido actualizado'), ('order_accepted', 'Pedido aceptado'), ('order_rejected', 'Pedido rechazado'), ('order_cancelled', 'Pedido cancelado'), ('payment_confirmed', 'Pago confirmado'), ('mp_webhook_paid', 'Pago confirmado por Mercado Pago'), ('shipment_accepted', 'Envío aceptado'), ('shipment_status_updated', 'Estado de envío actualizado'), ('driver_verification_updated', 'Verificación de repartidor actualizada')], max_length=64)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'), models.Index(fields=['object_type', 'object_id'], name='accounts_au_object__353b30_idx')],
            },
        ),
    ]
