# Generated by Django 5.2.16 on 2026-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('order_status_updated', 'Estado de pedido actualizado'), ('order_accepted', 'Pedido aceptado'), ('order_rejected', 'Pedido rechazado'), ('order_cancelled', 'Pedido cancelado'), ('payment_confirmed', 'Pago confirmado'), ('mp_webhook_paid', 'Pago confirmado por Mercado Pago'), ('shipment_accepted', 'Envío aceptado'), ('shipment_status_updated', 'Estado de envío actualizado'), ('driver_verification_updated', 'Verificación de repartidor actualizada'), ('dispute_updated', 'Disputa actualizada'), ('panel_entity_updated', 'Entidad del panel actualizada'), ('panel_entity_deactivated', 'Entidad del panel desactivada')], max_length=64),
        ),
    ]
