# Generated by Django 5.2.16 on 2026-07-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text='ID estable de la cuenta Google (sub del id_token).', max_length=64, null=True, unique=True),
        ),
    ]
