# Generated by Django 5.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_auditlog_action'),
        ('restaurants', '0018_productfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_restaurant',
            field=models.ForeignKey(
                blank=True,
                help_text='Local que el dueño opera ahora en la app.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='restaurants.restaurant',
            ),
        ),
    ]
