# Generated by Django 5.1.15 on 2026-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_active_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday_updated_at',
            field=models.DateTimeField(blank=True, help_text='Último cambio de fecha de cumpleaños (antiabuso).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Cumpleaños del cliente (beneficio de envío gratis ese día).', null=True),
        ),
    ]
