# Generated by Django 5.1.6 on 2026-06-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp para comprobantes de transferencia (opcional; si vacío, usa teléfono del negocio).', max_length=20),
        ),
    ]
