# Generated by Django 5.1.6 on 2026-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_set_demo_restaurant_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='accepting_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
