# Generated by Django 5.2.16 on 2026-07-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_productpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp de contacto del negocio (opcional; si vacío, usa teléfono).', max_length=20),
        ),
    ]
