# Generated by Django 5.2.16 on 2026-07-22 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_restaurant_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('min_select', models.PositiveSmallIntegerField(default=1, help_text='Mínimo de opciones a elegir (0 = opcional).')),
                ('max_select', models.PositiveSmallIntegerField(default=1, help_text='Máximo de opciones (1 = una sola).')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='restaurants.product')),
            ],
            options={
                'verbose_name': 'Grupo de opciones',
                'verbose_name_plural': 'Grupos de opciones',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurants.productoptiongroup')),
            ],
            options={
                'verbose_name': 'Opción de producto',
                'verbose_name_plural': 'Opciones de producto',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
