# Generated by Django 5.1.15 on 2026-08-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_restaurant_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pos_enabled',
            field=models.BooleanField(default=False, help_text='Si True, el restaurante puede usar ZinApp POS.'),
        ),
    ]
