# Generated by Django 5.1.6 on 2026-06-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_notification_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='orders_idem_created_6691b9_idx',
            old_name='orders_idem_created_idx',
        ),
    ]
