# Generated by Django 5.2.16 on 2026-07-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_extras_chat_disputes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mercadopago_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='mercadopago_status',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
