# Generated by Django 5.2.16 on 2026-07-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_mercadopago_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
