# Generated by Django 5.1.15 on 2026-08-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_stripe_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó la venta (cajero/staff POS).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('zinapp', 'ZinApp'), ('pos', 'POS'), ('phone', 'Teléfono'), ('takeaway', 'Para llevar')], db_index=True, default='zinapp', help_text='Origen del pedido (ZinApp, POS, teléfono, etc.).', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Cliente app. Nullable solo para ventas POS de mostrador.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default='', help_text='Dirección de entrega. Vacío en ventas POS de mostrador.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('online', 'Pago en línea'), ('card', 'Tarjeta'), ('other', 'Otro')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('online', 'Pago en línea'), ('card', 'Tarjeta'), ('other', 'Otro')], default='cash', max_length=20),
        ),
    ]
