# Generated by Django 5.1.15 on 2026-09-25 17:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_envio0_covers_35'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_benefit',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Beneficio de envío aplicado: birthday | loyalty. Vacío si ninguno.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento de envío por beneficio ZinApp. El fee original no se modifica.', max_digits=10),
        ),
    ]
