# Generated by Django 5.1.6 on 2026-06-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localservice',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localservice',
            name='category',
            field=models.CharField(choices=[('beauty', 'Belleza'), ('home', 'Hogar'), ('auto', 'Automotriz'), ('health', 'Salud'), ('food', 'Alimentos'), ('other', 'Otros')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='localservice',
            name='facebook',
            field=models.CharField(blank=True, help_text='Enlace o nombre de página de Facebook.', max_length=200),
        ),
        migrations.AddField(
            model_name='localservice',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuario o enlace de Instagram (ej. @salonmaria).', max_length=120),
        ),
        migrations.AddField(
            model_name='localservice',
            name='schedule',
            field=models.CharField(blank=True, help_text='Horario visible en la app (ej. Lun–Sáb 10:00–19:00).', max_length=120),
        ),
    ]
