# Generated by Django 5.1.15 on 2026-09-25 17:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0022_rewards_benefits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardProgramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_enabled', models.BooleanField(default=True)),
                ('loyalty_enabled', models.BooleanField(default=True)),
                ('loyalty_orders_required', models.PositiveSmallIntegerField(default=5)),
                ('delivery_discount_cap', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Tope máximo del descuento de envío (MXN).', max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración de beneficios',
                'verbose_name_plural': 'Configuración de beneficios',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_progress_event', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_progress_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de lealtad',
                'verbose_name_plural': 'Progresos de lealtad',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('birthday', 'Cumpleaños'), ('loyalty', 'Lealtad')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('reserved', 'Reservado'), ('consumed', 'Utilizado'), ('released', 'Liberado')], db_index=True, default='reserved', max_length=20)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Año calendario del cumpleaños (solo kind=birthday).', null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemption', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redención de beneficio',
                'verbose_name_plural': 'Redenciones de beneficio',
                'ordering': ['-reserved_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'birthday'), ('status__in', ['reserved', 'consumed'])), fields=('user', 'kind', 'year'), name='uniq_active_birthday_year')],
            },
        ),
    ]
